### ISSUE TITLE
413 Issue

### ISSUE THREAD

**Issue by FujiwaraChoki** [Bes-js/herc.ai#4]
I keep getting this error when using the NPM package on a question. Code is funcitoning 100%, I'm sure.

```
error - Error: Error: Request failed with status code 500
    at Hercai.question (node_modules\hercai\hercai.js:42:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async summarizeTranscript (webpack-internal:///(api)/./src/pages/api/summarize.ts:62:22)
    at async handler (webpack-internal:///(api)/./src/pages/api/summarize.ts:95:21)
    at async Object.apiResolver (node_modules\next\dist\server\api-utils\node.js:363:9)
    at async DevServer.runApi (node_modules\next\dist\server\next-server.js:488:9)
    at async Object.fn (node_modules\next\dist\server\next-server.js:750:37)
    at async Router.execute (node_modules\next\dist\server\router.js:253:36)
    at async DevServer.run (node_modules\next\dist\server\base-server.js:384:29)
    at async DevServer.run (node_modules\next\dist\server\dev\next-dev-server.js:741:20)
    at async DevServer.handleRequest (node_modules\next\dist\server\base-server.js:322:20) {
  page: '/api/summarize'
}```

**Comment by Bes-js** [comment]
use v3-beta model
